### ISSUE TITLE
Add wait mechanism in preprocess between append and subsequent get_field

### ISSUE THREAD

**Issue by youngblood** [ContinuumIO/topik#20]
I consistently encounter a KeyError for the "token_..." field when using the 'elastic' output_type.  I can see that the field exists if I manually view an individual document in the browser, but it appears there is some lag between appending the tokenized document and actually being able to retrieve it back.  I added a 1-second wait after the append loop and that appears to have solved the problem.

**Comment by msarahan** [comment]
OK, please do a PR.

**Comment by youngblood** [comment]
fixed by 'fix_elastic_token_append' branch (merged).
