### ISSUE TITLE
Readers should return (id, text)

### ISSUE THREAD

**Issue by DavidMertz** [ContinuumIO/topik#5]
I wanted to get checked in some changes I made before branches diverged too much (I made some refactoring changes, then got pulled away to training stuff for the last two weeks, unfortunately).  

In particular, I changed all the iter_documents*() functions to return not only the text of the thing being iterated, but a pair of (id, text) for each item.  I think iterating over a collection of texts is more general if there is an identity of the text returned (whether filename, pseudo-XPath for JSON, etc).

However, to support the previous APIs that simply get fed a sequence of texts, I added a lazy function topik.utils.unzip that will take an iterable over pairs and return two iterables of their first and second elements.  So the code change to get the original iterable of texts should just be:

        id_texts = iter_document_json_stream(something.json', "text")
        ids, texts = unzip(id_documents)

**Comment by msarahan** [comment]
This is currently how the new analogs, the raw data sources, work.  They return id, content by default, but have a method for getting a generator that returns only content.
