### ISSUE TITLE
change DictionaryCorpus implementation from list to dict

### ISSUE THREAD

**Issue by youngblood** [ContinuumIO/topik#50]

**Comment by msarahan** [comment]
For clarity, this: https://github.com/ContinuumIO/topik/blob/master/topik/intermediaries/raw_data.py#L256

This implies changes to import: https://github.com/ContinuumIO/topik/blob/master/topik/intermediaries/raw_data.py#L317
updating docs (inserting tokenized data) - this improvement will be very good:
https://github.com/ContinuumIO/topik/blob/master/topik/intermediaries/raw_data.py#L291
Yielding results (this will change to dictionary iteration; use ```for doc in self._documents.items()```:
https://github.com/ContinuumIO/topik/blob/master/topik/intermediaries/raw_data.py#L279
